logging:
  level:
    com.monthree: debug
spring:
  application:
    name: repository-user
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?namespace=monthree
    group: monthree
  consumer:
    check: false